Update git-graft

diff --git a/git_commands/git-graft b/git_commands/git-graft
--- a/git_commands/git-graft
+++ b/git_commands/git-graft
@@ -7,4 +7,15 @@ if [ -z "$onto" ]; then
     exit 1
 fi
 
-git rebase -i $(git merge-base --fork-point "$onto") --onto "$onto"
+readonly graftee=${2:-HEAD}
+fork_point=$(git merge-base --fork-point "$onto" "$graftee")
+if [ -z "$fork_point" ]; then
+    # Could not find a normal fork point; $graftee must not have branched off $onto
+    fork_point=$(git merge-base "$onto" "$graftee")
+    if [ -z "$fork_point" ]; then
+        echo "Could not find fork point between $graftee and $onto"
+        exit 2
+    fi
+fi
+
+git rebase --onto "$onto" "$fork_point" "$graftee"
